<template>
    <div id="TSP-graphing" class="demo">
        <div class="title">
            TSP solving by GA Graphing Tool
        </div>
        <el-popover
            placement="bottom"
            title="Guide"
            width="600"
            trigger="click"
        >
            <el-button class="button guide"
                slot="reference"
                size="small"
            >
                Guide
            </el-button>
            <h4>Instruction</h4>
            <p>
                This tool is a data visualization GUI for Travel Salesman Problem solved with Evolution Algorithm. <br>
                1. Start with selecting an instance(country) [and/or an algorithm]. <br>
                2. Drag the sliders in dashboard to alter parameters for browsing. <br>
                3. Graphs will show in left hand side area, as well as statistics in dashboard. <br>
            </p>
            <br>
            <h4>Datasets</h4>
            <p>
                All datasets the demo uses are generated by our algorithm. There's a few dataset of proper for demo. <br>
            </p>
            <br>
            <h4>Invalid Options</h4>
            <p>
                If an option (of instance selector or algorithm selector) is disabled, it means the relevant data or datafile is currently not available.
                I will make updates in the future. Some data could be too big to use (e.g. Canada).
            </p>
            <br>
            <h4>Chrome Mixed-Content Error</h4>
            <p>
                It's been reported on some version of Chrome, a http request from a https site will be blocked. Since I store the datasets on my website, which is http, in this case you'll need to enable the http request. <br>
                Click the lock icon in url bar to open site settings, for item <i>insecure content</i> choose allow. <br>
                (I'll be upgrading my site to https in the near future)
            </p>
        </el-popover>
        <el-button class="button to-github-repo"
            size="small"
            @click="jumpToGithubRepo()"
        >
            github
        </el-button>
        <el-button class="button to-project-report"
            size="small"
            @click="jumpToProjectReport()"
        >
            project report
        </el-button>
        <div class="main">
            <el-tabs class="tabs"
                type="border-card"
            >
                <el-tab-pane class="pane experiment"
                    :style="if_show_dashboard ? 'width: calc(100% - 400px);' : 'width: initial;'"
                    label="Experiment"
                >
                    <div>
                        <div class="title">Time Cost</div>
                        <div class="subtitle">time cost of each trial</div>
                        <div class="figure time-cost"
                            ref="figure_time_cost"
                        ></div>
                    </div>
                    <div class="divbar"></div>
                    <div>
                        <div class="title">Result</div>
                        <div class="subtitle">based on each generation's max、avg、min distance</div>
                        <div class="figure result"
                            ref="figure_result"
                        ></div>
                    </div>
                </el-tab-pane>
                <el-tab-pane class="pane evolution"
                    :style="if_show_dashboard ? 'width: calc(100% - 400px);' : 'width: initial;'"
                    label="Evolution"
                >
                    <div class="title">Distance Trend</div>
                    <div class="subtitle">based on each generation's max、avg、min distance</div>
                    <div class="figure evolution"
                        ref="figure_evolution"
                    ></div>
                </el-tab-pane>
                <el-tab-pane class="pane generation"
                    :style="if_show_dashboard ? 'width: calc(100% - 400px);' : 'width: initial;'"
                    label="Generation"
                >
                    <div class="figure generation"
                        ref="figure_generation"
                    ></div>
                </el-tab-pane>
                <el-tab-pane class="pane individual"
                    :style="if_show_dashboard ? 'width: calc(100% - 400px);' : 'width: initial;'"
                    label="Individual"
                >
                    <div class="figure individual"
                        ref="figure_individual"
                    ></div>
                </el-tab-pane>
                <el-tab-pane class="pane plain-map"
                    :style="if_show_dashboard ? 'width: calc(100% - 400px);' : 'width: initial;'"
                    label="Plain Map"
                >
                    <div class="figure plain-map" ref="figure_plain_map"></div>
                </el-tab-pane>
            </el-tabs>
            <el-select class="selector instance"
                v-model="using_instance"
                placeholder="select an instance"
                @change="useInstance()"
            >
                <el-option :key="0" :value="'WesternSahara'">WesternSahara</el-option>
                <el-option :key="1" :value="'Uruguay'">Uruguay</el-option>
                <el-option :key="2" :value="'Canada'" disabled>Canada</el-option>
            </el-select>
            <el-select class="selector algorithm"
                v-model="using_algorithm"
                placeholder="select an algorithm"
            >
                <el-option :key="0" :value="'basic'">basic</el-option>
                <el-option :key="1" :value="'advanced'">advanced</el-option>
            </el-select>
            <el-button class="dashboard button"
                @click="toggleDashboard()"
                size="medium"
            >
                Dashboard
            </el-button>
            <div class="dashboard panel"
                v-show="if_show_dashboard"
            >
                <div class="title">Trial</div>
                <el-slider 
                    v-model="trial_n"
                    :min="1"
                    :max="trial_all"
                    show-input
                    @change="drawEvolution();drawGeneration();drawIndividual();"
                ></el-slider>
                <div class="divbar"></div>
                <div class="title">Generation</div>
                <el-slider 
                    v-model="generation_n"
                    :min="1"
                    :max="generation_all"
                    show-input
                    @change="drawGeneration();drawIndividual();"
                ></el-slider>
                <div class="divbar"></div>
                <div class="title">Individual (best-worst)</div>
                <el-slider 
                    v-model="individual_n"
                    :min="1"
                    :max="2"
                    show-input
                    @change="drawIndividual();"
                ></el-slider>
                <div class="divbar"></div>
                <div class="title">Details</div>
                <div class="details">
                    <ul>
                        <li>
                            <ul>
                                Generation
                                <li>average distance: {{   using_generation_avg_distance   }}</li>
                                <li>shortest distance: {{   using_generation_best_distance   }}</li>
                                <li>longtest distance: {{   using_generation_worst_distance   }}</li>
                            </ul>
                        </li>
                        <li>
                            <ul>
                                Individual
                                <li>
                                    progress ratio: ???
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="divbar"></div>
                <div class="title">Route</div>
                <el-input class="route-sequence"
                    type="textarea"
                    :rows="5"
                    placeholder="here shows current route"
                    v-model="using_route">
                </el-input>
            </div>
        </div>
    </div>
</template>



<script lang="ts">
    import coords_WesternSahara from '../data/coords_WesternSahara'
    import coords_Uruguay from '../data/coords_Uruguay'
    // import coords_Canada from '../data/coords_Canada'
    import DrawingModule from './DrawingModule'

    import Vue from 'vue'

    export default Vue.extend
    ({
        components: 
        {
            
        },
        data()
        {
            return{
                using_instance: '',
                using_algorithm: 'advanced',

                if_show_dashboard: true,

                trial_n: 1,
                trial_all: 20,

                generation_n: 1,
                generation_all: 100,

                individual_n: 1,

                using_route: '',

                datasets:
                {
                    basic:
                    {
                        WesternSahara: null,
                        Uruguay: null,
                        Canada: null,
                    },
                    advanced:
                    {
                        WesternSahara: null,
                        Uruguay: null,
                        Canada: null,
                    }
                },

                using_generation_avg_distance: 0,
                using_generation_best_distance: 0,
                using_generation_worst_distance: 0,

                plain_map:
                {
                    WesternSahara: [[0],[0],[0]],
                    Uruguay: [[0],[0],[0]],
                    Canada: [[0],[0],[0]],
                }

            }
        },
        methods:
        {
            toggleDashboard() :void
            {
                this.if_show_dashboard = !this.if_show_dashboard
                console.log(this.datasets[this.using_algorithm].WesternSahara)
                console.log(this.datasets[this.using_algorithm].Uruguay)
            },

            // use instance //
            useInstance()
            {
                switch(this.using_instance)
                {
                    case 'WesternSahara':
                        // draw plain map ------------------------------------------------------------------------------
                        DrawingModule.drawPlainMap(coords_WesternSahara, this.$refs.figure_plain_map)
                        // fetch target data ---------------------------------------------------------------------------
                        if(this.datasets[this.using_algorithm].WesternSahara == null)
                        {
                            DrawingModule.fetchData(this.using_algorithm + '_WesternSahara')
                            .then
                            (
                                (response:any) =>
                                {
                                    if(response.data != 'no such dataset')
                                    {
                                        this.$notify({title: 'data fetched successfully', message: ''})

                                        this.datasets[this.using_algorithm].WesternSahara = response.data

                                        this.drawWesternSahara()
                                    }
                                    else
                                    {
                                        this.$notify(
                                            {
                                                title: 'data unavailable',
                                                message: `Server responded: ${'no such dataset'}`,
                                            }
                                        )
                                    }
                                }
                            )
                        }
                        // while has data, draw ------------------------------------------------------------------------
                        else
                        {
                            this.drawWesternSahara()
                        }
                        break
                    case 'Uruguay':
                        // draw plain map ------------------------------------------------------------------------------
                        DrawingModule.drawPlainMap(coords_Uruguay, this.$refs.figure_plain_map)
                        // fetch target data ---------------------------------------------------------------------------
                        if(this.datasets[this.using_algorithm].Uruguay == null)
                        {
                            DrawingModule.fetchData(this.using_algorithm + '_Uruguay')
                            .then
                            (
                                (response:any) =>
                                {
                                    if(response.data != 'no such dataset')
                                    {
                                        this.$notify({title: 'data fetched successfully', message: ''})

                                        this.datasets[this.using_algorithm].Uruguay = response.data

                                        DrawingModule.drawExperiment(
                                            this.datasets[this.using_algorithm].Uruguay,
                                            this.generation_all,
                                            this.$refs.figure_time_cost, 
                                            this.$refs.figure_result
                                        )
                                    }
                                    else
                                    {
                                        this.$notify({title: 'data unavailable', message: ''})
                                    }
                                }
                            )
                        }
                        else
                        {
                            // draw experiment - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                            DrawingModule.drawExperiment(
                                this.datasets[this.using_algorithm].Uruguay,
                                this.generation_all,
                                this.$refs.figure_time_cost, 
                                this.$refs.figure_result
                            )
                        }
                        break
                    case 'Canada':
                        // DrawingModule.drawPlainMap(coords_Canada, this.$refs.figure_plain_map)
                        // Canada dataset is abandoned as it's way too big //
                        break
                    default:
                        break
                }
            },

            jumpToGithubRepo() :void
            {
                window.open('https://github.com/Wolff-H/COMP-3-201', '_blank')
            },

            jumpToProjectReport() :void
            {
                window.open('https://github.com/Wolff-H/COMP-3-201/blob/master/Project/COMP3201FinalProjectReport.pdf', '_blank')
            },

            // 0 //
            drawExperiment()
            {
                // draw experiment - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                DrawingModule.drawExperiment(
                    this.datasets[this.using_algorithm].WesternSahara,
                    this.generation_all,
                    this.$refs.figure_time_cost, 
                    this.$refs.figure_result,
                )
            },
            drawEvolution()
            {
                // draw evolution - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                DrawingModule.drawEvolution(
                    this.datasets[this.using_algorithm].WesternSahara,
                    this.$refs.figure_evolution,
                    this.generation_all,
                    this.trial_n,
                )
            },
            drawGeneration()
            {
                // draw generation - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                let dashboard_data = 
                DrawingModule.drawGeneration(
                    this.datasets[this.using_algorithm].WesternSahara,
                    this.$refs.figure_generation,
                    this.generation_all,
                    this.trial_n,
                    this.generation_n,
                )
                this.using_generation_avg_distance = dashboard_data.avg
                this.using_generation_best_distance = dashboard_data.best
                this.using_generation_worst_distance = dashboard_data.worst
            },
            drawIndividual()
            {
                // draw individual - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
                this.using_route =
                DrawingModule.drawIndividual(
                    this.datasets[this.using_algorithm].WesternSahara,
                    this.$refs.figure_individual,
                    this.generation_all,
                    this.trial_n,
                    this.generation_n,
                    this.individual_n,
                    this.plain_map.WesternSahara,
                )
            },


            // 1 //
            drawWesternSahara()
            {
                this.drawExperiment()
                this.drawEvolution()
                this.drawGeneration()
                this.drawIndividual()
            }
        },
        mounted()
        {
            DrawingModule.getTestJsonFile()
            this.plain_map.WesternSahara = DrawingModule.parseCoords(coords_WesternSahara)

            // automatically fetched the default dataset //
            this.$nextTick(
                () =>
                {
                    this.using_instance = 'WesternSahara'
                    this.useInstance()
                }
            )
        },
    })
</script>



<style lang="stylus">
    @import _colorset
    // stateful ////////////////////////////////////////////////////////////////////////////////////////////////////////

    // basic ///////////////////////////////////////////////////////////////////////////////////////////////////////////
    #TSP-graphing.demo
        padding 8px

        >.title
            display flex
            align-items center
            justify-content center
            font-size 24px
            height 40px
        
        .button.guide
            position absolute
            left 8px
            top 10px

        .button.to-github-repo
            position absolute
            left 80px
            top 10px
        
        .button.to-project-report
            position absolute
            left 142px
            top 10px

        >.main
            position relative
            height 1000px
            
            >.tabs
                height 100%

                .pane
                    overflow-x auto
                    overflow-y: hidden
                    
                    .title
                        font-weight bold
                        color $black60

                    .subtitle
                        color $black60
                    
                    .figure.time-cost, .figure.result
                        height 400px
                        width 1850px
                    
                    .figure.plain-map
                        height 900px
                        width 1850px
                    
                    .figure.evolution, .figure.generation, .figure.individual
                        height 900px
                        width 1850px
                
                .divbar
                    width 100%
                    border-bottom 1px solid $black20
                    margin 5px 0px 5px 0px
            
            >.selector.instance, >.selector.algorithm
                position absolute
                top 0px
                height 40px
                width 200px

                input
                    border-radius 0px
                    background-color $black03
                    
            >.selector.instance
                right 600px
            
            >.selector.algorithm
                right 400px

            >.dashboard.button
                position absolute
                right 0px
                top 0px
                height 40px
                border-radius 0px
                width 400px
                background-color $black03

            >.dashboard.panel
                position absolute
                top 40px
                right 0px
                height (1000 - 40)px
                width 401px
                background-color $black03
                border 1px solid $black10
                border-left-width 2px
                border-top none
                padding 10px

                >.title
                    font-weight bold
                    color $black60
                    padding 5px 0px 10px 0px
                
                >.divbar
                    width 100%
                    border-bottom 1px solid $black20
                    margin 15px 0px 10px 0px

                .el-slider__button-wrapper, .el-slider__button.hover, .el-slider__button:hover
                    cursor pointer

                >.details

                    li
                        list-style-type none
                        color $black60
                        margin-left 20px
                    
                    >ul>li>ul>li
                        font-size 14px
                
                .route-sequence>textarea
                    font-size 24px



</style>
